
from typing import TypeVar, Generic


__all__ = [
    "Settings"
]


T = TypeVar("T")


class Settings(Generic[T]):
    def __init__(self, *args: T, **kwargs: T) -> None: ...
    def __setitem__(self, key: T, item: T) -> None: ...
    def __getitem__(self, key) -> T: ...
    def __repr__(self) -> T: ...
    def __len__(self) -> T: ...
    def __delitem__(self, key) -> None: ...
    def __contains__(self, item) -> T: ...
    def __iter__(self) -> T: ...
    def __add__(self, other) -> None: ...
